Added svg icon
ExpressHermes/JokesApp pull request #11
Opened 2021-12-07 13:02 UTC by artimanputra

This PR is regarding issue #3. Added SVG for font awesome icons.

2021-12-07 13:32 UTC, ExpressHermes requested changes
This needs additional work. 

@artimanputra Check these out to understand how you can replace the icons:
- [Stack Overflow answer](https://stackoverflow.com/a/52427428/13398404)
- [Blog](https://www.wouterbulten.nl/blog/tech/blog-optimization-replacing-font-awesome-with-svg/)

Ping on slack channel if you don't understand the process

2021-12-14 04:10 UTC, ExpressHermes commented
Hey @artimanputra the changes look good. Can you post a few screenshots of the updated pages so I can verify the icons?

2021-12-14 04:20 UTC, artimanputra commented
> Hey @artimanputra the changes look good. Can you post a few screenshots of the updated pages so I can verify the icons?

Sure.

2021-12-14 14:33 UTC, artimanputra commented
> Hey @artimanputra the changes look good. Can you post a few screenshots of the updated pages so I can verify the icons?

@ExpressHermes Here is the screenshot.
![Screenshot_3](https://user-images.githubusercontent.com/79042027/146017958-75bffdc3-7273-4c91-8bc1-80a39e1c53a7.png)

2021-12-15 12:40 UTC, ExpressHermes approved these changes

2021-12-15 12:40 UTC, merged