Added option to generate different genre of jokes
ExpressHermes/JokesApp pull request #8
Opened 2021-12-04 10:43 UTC by kartikeyjangir

Added option to generate different genre of jokes and also added nodemon package

2021-12-04 11:16 UTC, kartikeyjangir commented
Added option to generate different genre of jokes and added .env file to hide api keys

2021-12-05 14:14 UTC, ExpressHermes commented on app.js
> +app.get("/chuck", function(req, res) {
Making a separate endpoint to go to get different jokes is not ideal. If we add 5-6 genres, we will end up with 5-6 endpoints all doing the same thing(calling an API and showing results). Make all the changes in the same endpoint and use functions and conditions to show the result.

One way is when a genre is selected by the user(user clicked Chuck Norris joke button on the home page, we can use the button to send input back to the nodejs app to understand which genre user wants and then show them the jokes based on that.

2021-12-05 14:15 UTC, ExpressHermes commented on package.json
> +    "start": "nodemon app.js"
Remove `nodemon`. This is okay for development not for prod.

2021-12-05 14:20 UTC, ExpressHermes requested changes
Please make the requested changes!

2021-12-05 14:20 UTC, ExpressHermes commented on views/getJokes.ejs
> +             <% if(data.urlName==="dadJokes") { %>
this if-else statement assumes that there are only two types of jokes that can be returned(Dad Jokes and Chuck Norris). Instead, we will have more types of jokes. So use only if statement for each type of joke without using else.

Pseudocode:
```
if(isDadJoke) {
    // show the joke
}

if (isChuckNorrisJoke) {
    ...
}

if (anothTypeOfJoke) {
    ...
}
```

2021-12-05 14:20 UTC, ExpressHermes commented on views/partials/jokeTypes.ejs
> +    <button style="margin-bottom:20px; background-color: #4ECDC4; border: none; border-radius: 10px; font-size: 22px;"> <a href="/" style="color: white;">Get Dad Jokes</a></button>
Use css file instead of inline css

2021-12-05 14:20 UTC, ExpressHermes commented
Also, remove `package-lock.json` file.

2021-12-10 17:37 UTC, closed without merging